### ISSUE TITLE
[bug]wax site demo run failed

### ISSUE THREAD

**Issue by liode1s** [FACINGS/eospyo#10]
Hello, I tried to use the Wax transfer Wax example, and found that the returned data is always 500 error message "eosio_assert_message assertion failure"
```
   actions: [{
     account: 'eosio.token',
     name: 'transfer',
     authorization: [{
       actor: wax.userAccount,
       permission: 'active',
     }],
     data: {
       from: wax.userAccount,
       to: 'eosio',
       quantity: '0.00000001 WAX',
       memo: '',
     },
   }]
```
想搞action这样。错误提示
```
{
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 3050003,
        "name": "eosio_assert_message_exception",
        "what": "eosio_assert_message assertion failure",
        "details": [
            {
                "message": "assertion failure with message: get",
                "file": "wasm_interface.cpp",
                "line_number": 1131,
                "method": "eosio_assert"
            }
        ]
    }
}
```
I observed the eosjs serialization code. and waxblock.io where the quantity field is the asset type

**Comment by edinhodiluviano** [comment]
Hello @liode1s and thanks for the issue.
We used to support transfer actions, like this [old example](https://github.com/FACINGS/eospyo/blob/fe8d767c7f8cf8d4e5cf1f9d0ff1f8eb31261e10/examples/transfer.py)
However since we've changed the serialization method, unfortunately we dropped the transfer feature. Surely we want to bring it back as soon as possible, but for the lack of resources we can't do it right away.
But if you're willing to create an `Asset` type and send a PR with it, we'd be really happy to check and even merge it ; )

Also we'd tend to not support an old version of the lib right now. But if you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the error [running against the test nodeos](https://github.com/FACINGS/eospyo#run-tests) contained in this project I can take a quick look at it.

**Comment by edinhodiluviano** [comment]
Hey @liode1s, sorry for the delay. But has been a while we updated to version 0.6 and it supports transfers now. Let us know if [this example](https://github.com/FACINGS/eospyo/blob/main/examples/transfer.py) does not work for you. Thanks.
