### ISSUE TITLE
No offense, just a question...

### ISSUE THREAD

**Issue by tianwangchn** [FACINGS/eospyo#7]
There have been other easy-to-use Python EOS API tools here for a long time. 
Is this project reinventing the wheel?

For example: https://github.com/learnforpractice/pyeoskit

**Comment by edinhodiluviano** [comment]
Hello @tianwangchn ,
Yes, you're right. There are some other python projects. But we don't see ourselves reinventing the wheel.
For a better view, I'll list some here and why we haven't choose them (the order has no meaning):

- [pyeoskit](https://github.com/learnforpractice/pyeoskit) (your example):
They have a great project. It used to be heavily based on UUOSKit, so I'll focus on just one of them.
If we were to use one of them, we'd go with the parent project.
(ps.: It seems that pyeoskit made important changes recently. I'd need to update myself on those...)

- [UUOSKit](https://github.com/uuosio/UUOSKit/):
It seems they found a clever way to use `libuuoskit` binaries using cython.
That is a good idea since we need to maintain only one codebase and they may get the benefits from a pre-compiled code.  
But we are quite concerned by the use of an external wallet (in this case, a file in the disk). That would behave like a global state. Also it is a problem if you're to use non-resilient or read-only file systems (like some containers or function-as-a-service computing)

- [eospy](https://github.com/eosnewyork/eospy):
Their project is similar to ours.
However it seems that the development is slow recently. Personally, I'd probably go with this one if it was active.

- [µEOSIO](https://github.com/EOSArgentina/ueosio):
We're based on them. Also we use some of their code in ours.
I can't state how thankful we are for this project and people to exist. hehehe
Our api, however, is very different. Also we're using [nodeos rpc calls](https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index/) to serialize the data.

As you can see, we haven't started from scratch. We used other projects' codes and ideas into this project. This is common (and, I believe, healthy) for the open source ecosystem.
Maybe, in the future, all projects can converge to just one single lib and all others be deprecated. I believe this would mean that we found a solution that fits many (hopefully all) use cases.
Meanwhile we need something that fits our needs (easy api, easy to parallelize, works well with some cloud tools, etc) and want to share with others that may face the same problems.

**Comment by tianwangchn** [comment]
Hi edinhodiluviano,
Great! Thank you for your reply which answered my doubts.
I wish eospyo can become a powerful and easy-to-use tool. Happy coding~
